//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAndInvoicingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Master()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Name { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Address { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string City { get; set; }
        [System.ComponentModel.DataAnnotations.StringLength(10)]

        [DataType(DataType.PostalCode)]
        public string Pincode { get; set; }

        [DataType(DataType.PhoneNumber)]
        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public string ContactNumber { get; set; }

        
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        [DataType(DataType.EmailAddress)]
        public string EmailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
