//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAndInvoicingSystem3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderInvoiceSystemEntities : DbContext
    {
        public OrderInvoiceSystemEntities()
            : base("name=OrderInvoiceSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_Master> Customer_Master { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_line_item> Order_line_item { get; set; }
        public virtual DbSet<Product_Master> Product_Master { get; set; }
    }
}
