//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAndInvoicingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_line_item
    {
        public int ID { get; set; }
        public int OrderId { get; set; }
        public int ProductID { get; set; }

        [System.ComponentModel.DataAnnotations.Range(1, 1000)]
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal GST { get; set; }
        public decimal Total_price { get; set; }

        // for order business logic
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public decimal GSTPrev { get; set; }
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public decimal Total_pricePrev { get; set; }

        public virtual Product_Master Product_Master { get; set; }
    }
}
