//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAndInvoicingSystem3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Master()
        {
            this.Order_line_item = new HashSet<Order_line_item>();
        }
    
        public int Id { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Product_name { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string Category { get; set; }
        public decimal Rate { get; set; }
        public decimal GST_rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_line_item> Order_line_item { get; set; }
    }
}
